# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c44ae6d0551f2dc2d21f73728495075f4758d595775a04f6d782c6b14a6ccf932ba4465e1f32a0f8d2e5bb8ff7a0ea807c9abd30945b9636d92f18093fe47ff

test:
  secret_key_base: 095e7f1ed6f71c1125f11298f122535eaed022a9c59e38419460584e7100884c2d71b3b85dd4177177219dfb228657be4d62f978a7cecb12a240ed38510760cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
